#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    
    elem = arr[n-1]
    for i in range(n-2, -1, -1):
        arr[i + 1] = arr[i]
        temp = [str(j) for j in arr]
        print(" ".join(temp))
        if elem > arr[i - 1] or i == 0:
            arr[i] = elem
            temp = [str(j) for j in arr]
            print(" ".join(temp))
            break
    # Write your code here

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
